<?php

use App\Core\Csrf;
use App\Core\Session;

function base_path(): string
{
    static $base = null;
    if ($base === null) {
        $scriptName = $_SERVER['SCRIPT_NAME'] ?? '';
        $dir = str_replace('\\', '/', dirname($scriptName));
        $base = $dir === '/' ? '' : $dir;
    }
    return $base;
}

function url(string $path = ''): string
{
    return base_path() . $path;
}

/**
 * Absolute URL (scheme + host), for contexts with no browser base URL of
 * their own — outbound emails, including those generated by CLI cron
 * scripts (bin/send_overdue_reminders.php, bin/generate_recurring_invoices.php)
 * where $_SERVER['HTTP_HOST'] doesn't exist, hence the config['app']['url'] fallback.
 */
function full_url(string $path = ''): string
{
    if (!empty($_SERVER['HTTP_HOST'])) {
        $scheme = $_SERVER['REQUEST_SCHEME'] ?? (($_SERVER['HTTPS'] ?? '') === 'on' ? 'https' : 'http');
        return $scheme . '://' . $_SERVER['HTTP_HOST'] . url($path);
    }

    static $appUrl = null;
    if ($appUrl === null) {
        $config = require dirname(__DIR__, 2) . '/config/config.php';
        $appUrl = rtrim($config['app']['url'] ?? 'http://localhost', '/');
    }

    return $appUrl . $path;
}

/** Absolute URL to an organization's uploaded logo, or '' if none is set. */
function org_logo_url(?int $organizationId, array $company): string
{
    if ($organizationId === null || empty($company['logo_path'])) {
        return '';
    }
    return full_url('/org-logo/' . $organizationId);
}

function redirect(string $path): void
{
    header('Location: ' . url($path));
    exit;
}

function old(string $key, $default = '')
{
    return $_SESSION['old'][$key] ?? $default;
}

function flashes(): array
{
    return Session::getFlashes();
}

function csrf_field(): string
{
    return Csrf::field();
}

function is_post(): bool
{
    return ($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST';
}

function input(string $key, $default = '')
{
    $value = $_POST[$key] ?? $default;
    return is_string($value) ? trim($value) : $value;
}

function require_post_field(array $errors, string $key, string $label): array
{
    if (empty($_POST[$key])) {
        $errors[] = "Le champ « {$label} » est obligatoire.";
    }
    return $errors;
}
